language: c
addons:
  apt:
    packages:
    - bc
    - gcc-arm-linux-gnueabi
    - u-boot-tools
    - debian-archive-keyring
    - debootstrap
script: make
deploy:
  provider: releases
  api_key:
    secure: BMXwK6VLzZwiB+wCDQuFMWxLwZXy4Baj8YtALDTe24vjl1D8/dB2B30PkddZOnDWZq09H9u1CJmhEYhCqPcPQpEgHdlfuxWvsslLogbRER5So7IoxUPGOPtJxD4iX7wN/ZVmD7gBWL1rmobqfh7ZRkUmc9sQj7/+deWTieqq3v6EvgY3pIanlNGen/8Wd9ifEVceM9tTw8lMdN9kbSHf3i2mzmIA6/MW5UZaXlnEM6ULU/2XYesG/OoRquZBrxhAfFm4lCGy3hrUOLUSTg8jyD7fLlpjLUL8Fww7oVSgijAxsieoSenCwO72BijWA/rXCSjJWQijnFziBiILNPsQsTCJkuQbWcXFDj8I6WCUTNdPEuF35CRlgpxOnZm74Kpe8DcsYkqrk3n3lKk1MiKHOv+ImZtApWlWTaZLwvlhOHFVekowiX3/eF95xLmnmwB/mzEi8tPDxOI/8ivYliae+h9xCUX+DIx0yYkMmO+2W7G50vKnVUVoOU5j25g+51kV+MHPeDSI5Na8//fuHq9uCW7A8zBRC4H2uNOalbclhVEs0Bxd4QUAZytBnbGehK0vuFEJVB6HlDLU3xOerzGanqNUN8fLdoscmpGjcLcEt/o/hV01Y17iPRAoXCKViopV8xOL6LeISjv7GMTZsMm0iPYY4pkNCGHNcdZBEfdSdM4=
  file:
  - boot.zip
  - rootfs.tar.gz
  on:
    tags: true
