#!/bin/sh -eux
umask 022

/usr/sbin/multistrap -f multistrap.conf

mv tmp/sbin/init tmp/sbin/init.stock
# fstab based on create_fstab_header from partman-target
cp -r ship/. tmp

tar -czf "$1" -C tmp .
rm -rf tmp
