#!/bin/sh
{
	export PATH &&

	read -p "Hostname: " hostname &&
	echo "$hostname" >/etc/hostname &&

	# based on netcfg_write_common from netcfg
	cat >/etc/hosts <<EOF
127.0.0.1	localhost
127.0.1.1	$hostname

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
EOF

	mv /sbin/init.stock /sbin/init &&

	/var/lib/dpkg/info/base-passwd.preinst install &&
	DEBIAN_FRONTEND=teletype dpkg --configure -a &&

	read -p "Username for your account: " username &&
	adduser --gecos "" "$username" &&
	adduser "$username" sudo &&

	exec /sbin/init
} || exec /bin/sh
